### ISSUE TITLE
Switching symbooglix to MIT license (instead of BSD-2)

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/symbooglix#41]
So I am a member of a team what has been working on automatic testing of Dafny programs. We are really interested in potentially rebooting symbooglix to use it in this context. Given that the team involves Amazon employees, to be able to contribute to symbooglix, it would be really helpful if its license would be the same as other Boogie-related projects such as Boogie, Corral, Dafny, which are all under MIT license.

Could we place switch symbooglix to MIT license to make it totally in sync with other related projects?

Please let me know. Thanks!

**Comment by zvonimir** [comment]
Tagging @delcypher, @afd, @ccadar. Thanks!

**Comment by ccadar** [comment]
@zvonimir I am glad to hear that.  I personally don't mind switching licenses, but just curious, which part of the BSD-2 license is problematic for Amazon?  Both are liberal licenses, and they look quite similar to me.

**Comment by zvonimir** [comment]
I am not sure if "problematic" is the right term here. It will likely raise questions though since all other Boogie-related tools are under MIT license, and this one is an outlier in that sense.
Even if we put Amazon aside, it would be really nice if all these tools were under the same license and uniform in that sense. And as your wrote, given that they are really similar, to me it seems that switching maybe (hopefully?) wouldn't be a big deal.
I am not a license expert though.

**Comment by ccadar** [comment]
OK, I understand.  And as I said, I don't mind the switch.  @delcypher , @afd ?

**Comment by afd** [comment]
I am OK with the switch.
